datasetId: "64a403f958e3f60011a0f80d"
entryFile: 'tensorleap.py'
include:
  - tensorleap.py
  - armbench_segmentation/__init__.py
  - armbench_segmentation/preprocessing.py
  - armbench_segmentation/visualizers.py
  - armbench_segmentation/metadata.py
  - armbench_segmentation/gcs_utils.py
  - armbench_segmentation/metrics.py
  - armbench_segmentation/utils/general_utils.py
  - armbench_segmentation/utils/ioa_utils.py
  - armbench_segmentation/yolo_helpers/yolo_utils.py
  - tests/test_tensorleap.py