max_sequence_length: 384
max_answer_length: 20
LABELS:
  - "start_idx"
  - "end_idx"
PAD_TOKEN: ""
TRAIN_SIZE: 1000
VAL_SIZE: 1000
CHANGE_INDEX_FLAG: true
input_keys:
  - "input_ids"
  - "token_type_ids"
  - "attention_mask"
  - "offset_mapping"





