projectName = "coco_pytorch"
organization = "demo"
#framework = "tensorflow"
datasetName = "COCO"
bucketName = "example-datasets-47ml982d"


# config.toml schema version; you probably don't have to change this.
version = "0.1.0"

# Location of integration files (relative to .tensorleap directory)
[integration]
model = "model.py"
dataset = "dataset.py"
loss = "loss.py"
