projectName = "coco_segmentation"
organization = "dani"
#framework = "tensorflow"
datasetName = "coco_deeplab2"
bucketName = "example-datasets-47ml982d"
modelType = "onnx"

# config.toml schema version; you probably don't have to change this.
version = "0.1.0"

# Location of integration files (relative to .tensorleap directory)
[integration]
model = "model.py"
dataset = "dataset.py"
loss = "loss.py"
