NUMBER_OF_SAMPLES: 20000
BUCKET_NAME: 'example-datasets-47ml982d'
PROJECT_ID: 'example-dev-project-nmrksf0o'

MAX_FEATURES: 10000
SEQUENCE_LENGTH: 512

MODEL_NAME: "fabriceyhc/bert-base-uncased-imdb"

LABELS_NAMES:
  - neg
  - pos

