BUCKET_NAME: 'example-datasets-47ml982d'
PROJECT_ID: 'example-dev-project-nmrksf0o'
BASE_PATH: "imdb"

MAX_FEATURES: 10000
SEQUENCE_LENGTH: 512

MODEL_NAME: "fabriceyhc/bert-base-uncased-imdb"

LABELS_NAMES:
  - neg
  - pos





